version: "3.9"
name: webpep-web-frontend-dev

services:
  db:
    image: code.moonstar-x.dev/webpep/neo4j-db:latest
    restart: unless-stopped
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - TZ=America/Guayaquil
      - NEO4J_AUTH=none

  cache:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - TZ=America/Guayaquil

  python_rest_api:
    image: code.moonstar-x.dev/webpep/python-rest-api:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      - TZ=America/Guayaquil
      - NEO4J_DB_URI=bolt://db:7687
      - REDIS_URI=redis://cache:6379
